### ISSUE TITLE
Shelf not working on Flutter Web

### ISSUE THREAD

**Issue by randomdude583** [dart-lang/shelf#137]
I am running a web server, and it works fine if run from the console, or run on Android, but crashes when run in Flutter Web. the error log is shown below:

```
Error: Unsupported operation: ServerSocket.bind
    at Object.throw_ [as throw] (http://localhost:49818/dart_sdk.js:4461:11)
    at Function._bind (http://localhost:49818/dart_sdk.js:57214:17)
    at Function.bind (http://localhost:49818/dart_sdk.js:57202:32)
    at Function.bind (http://localhost:49818/dart_sdk.js:173876:30)
    at Function.bind (http://localhost:49818/dart_sdk.js:167416:32)
    at serve (http://localhost:49818/packages/shelf/src/io_server.dart.lib.js:132:70)
    at serve.next (<anonymous>)
    at runBody (http://localhost:49818/dart_sdk.js:37119:34)
    at Object._async [as async] (http://localhost:49818/dart_sdk.js:37150:7)
    at Object.serve (http://localhost:49818/packages/shelf/src/io_server.dart.lib.js:130:18)
    at startServer (http://localhost:49818/packages/test_flutter_api/main.dart.lib.js:544:36)
    at startServer.next (<anonymous>)
    at runBody (http://localhost:49818/dart_sdk.js:37119:34)
    at Object._async [as async] (http://localhost:49818/dart_sdk.js:37150:7)
    at Object.startServer (http://localhost:49818/packages/test_flutter_api/main.dart.lib.js:518:18)
    at Object.main$ [as main] (http://localhost:49818/packages/test_flutter_api/main.dart.lib.js:515:10)
    at main$ (http://localhost:49818/web_entrypoint.dart.lib.js:14:12)
    at main$.next (<anonymous>)
    at http://localhost:49818/dart_sdk.js:37099:33
    at _RootZone.runUnary (http://localhost:49818/dart_sdk.js:36953:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:49818/dart_sdk.js:32045:29)
    at handleValueCallback (http://localhost:49818/dart_sdk.js:32592:49)
    at Function._propagateToListeners (http://localhost:49818/dart_sdk.js:32630:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49818/dart_sdk.js:32356:27)
    at Object._microtaskLoop (http://localhost:49818/dart_sdk.js:37214:13)
    at _startMicrotaskLoop (http://localhost:49818/dart_sdk.js:37220:13)
    at http://localhost:49818/dart_sdk.js:32847:9
```

Any ideas?

**Comment by allentv** [comment]
If I understand correctly, `shelf` is meant to run as s standalone program in the Dart VM rather than through the browser since it has to bind and listen to incoming connections.

**Comment by kevmoo** [comment]
`shelf.dart` should work great anywhere.

Anything that imports `shelf_io.dart` will need access to `dart:io` – which won't work on the web.

**Comment by jalakoo** [comment]
I recently encountered the same error as @randomdude583 when running Flutter Web. Worked fine in an iOS Simulator and on device.

**Comment by kevmoo** [comment]
Yup. You cannot listen on the web. Any path that imports `shelf_io.dart` will likely fail on the web.

**Comment by jalakoo** [comment]
Bummer. But thanks for quick reply @kevmoo

**Comment by kevmoo** [comment]
@wailashraf71 – I don't see why not. Try it!

**Comment by developeranshul1986** [comment]
Hi
Did you find any solution for this?

**Comment by kevmoo** [comment]
shelf uses `dart:io` – this is not available on a browser.
